#!/usr/bin/python
import os,time
from datetime import datetime as d
import hashlib as hs
import ntpath
print("###############filename##############")
print(ntpath.basename("/home/j1axs01/jc/test.txt"))
print("###############extension###############")
print(os.path.splitext("/home/j1axs01/jc/test.txt")[1])
print(time.gmtime(os.path.getmtime("/home/j1axs01/jc/test.txt")))
print("##############################")
print(os.stat("test.txt"))
print(os.path.getmtime("/home/j1axs01/jc/test.txt"))
sha=hs.sha256("test.txt")
num_lines = sum(1 for line in open("test.txt"))
print("################row counts##############")
print(num_lines)
print("###############sha256###############")
print(sha.hexdigest())
